# Generated by Django 3.0.1 on 2020-03-13 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followuser',
            name='followed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_by', to='social.MyProfile'),
        ),
        migrations.AlterField(
            model_name='followuser',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Profile', to='social.MyProfile'),
        ),
        migrations.AlterField(
            model_name='postcommet',
            name='commited_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.MyProfile'),
        ),
        migrations.AlterField(
            model_name='postlike',
            name='liked_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.MyProfile'),
        ),
    ]
